cask_args appdir: '/Applications'
cask 'firefox'        # browser
cask 'google-chrome'  # browser
cask 'avast'          # security
cask 'lastpass'       # security
cask 'spotify'        # music
cask 'slack'          # communication
cask 'steam'          # games
cask 'xquartz' 
