cask_args appdir: '/Applications'

cask 'java' unless system '/usr/libexec/java_home --failfast'
brew 'maven'

cask 'atom'                      # open source text editor
cask 'virtualbox'                # Virtualbox
cask 'virtualbox-extension-pack' # Virtualbox
cask 'vagrant'                   # virtual system automation
cask 'dockertoolbox'             # linux container automation
cask 'puppet'                    # change configuration
cask 'chefdk'                    # change configuration
